#!/bin/sh -x

rm -f portno core
./server > portno &
sleep 3
portno=`cat portno`
for i in 0 1 2 3 4 ; do
    ( ./client ${portno} < File.cc & ./client ${portno} < File.cc & ./client ${portno} < File.cc & ./client ${portno} < File.cc & ./client ${portno} < File.cc ; wait ) ;
    sleep 5			# wait for core to be dumped
if [ -f core ] ; then break; fi
    echo "successful completion"
done
